### ISSUE TITLE
why dose the warlock page only have p4 gearset

### ISSUE THREAD

**Issue by exolution** [wowsims/sod#1199]
I found p5 gearset in the repo code, but I couldn't find it on the page

Could it be caused by some local cache? However, it still doesn't work even when I use Chrome's incognito mode(no cache).

**Comment by kayla-glick** [comment]
Hey @exolution 👋 

The reason it hasn't been updated it mostly due to time. We don't have many developers left working on our Season of Discovery site and with the fast pacing of Phases 5, 6, and now 7 coming up plus compiling links each phase I haven't had time to go in and add presets for every spec

**Comment by kayla-glick** [comment]
I've gone ahead and imported phase 6 data for warlock dps (not tanks, though). I can't guarantee that it will be as polished/flexible as other phases but it will at least provide options for players

**Comment by exolution** [comment]
So that's how it is. I understand now. Thank you for your efforts.
