### ISSUE TITLE
Missing/Wrong buffs

### ISSUE THREAD

**Issue by adocoD** [wowsims/sod#172]
Currently applied in the hunter melee sim:

- Blessing of Might 4
- Battle Shout 4
- Aspect of the Hawk 2

Missing;

- Arcane Intellect
- Mark of the Wild
- Heart of the Lion
- Leader of the Pack
- Various consumables

Currently wrong

- Aspect of the Hawk 2 -> should be 4

Might be more buffs missing.

**Comment by kayla-glick** [comment]
Buffs and maybe consumes seem to be updated but aspect of the hawk ranks 3 and 4 are still missing

**Comment by adocoD** [comment]
I see no difference in my sims. Both the results UI and the log it gives show none of those buffs.

**Comment by kayla-glick** [comment]
Oh I see they're missing from the Buffs tab under results

**Comment by kayla-glick** [comment]
Ok so I looked into this a bit. The reason you're not seeing some general buffs like intellect, motw, etc is because we simply add stats rather than creating auras to track the buffs. This keeps the list of auras shorter to not bloat the Buffs tab or the Aura list in the APLs with extra raid buff auras. The reason we have have some buffs like Blessing of Might and Battle Shout as auras is because they may be used in rotations.

It looks like the Aspect of the Hawk Rank 2 issue is because the phase 2 APL is using rank 2, so I can fix that, though!
