### ISSUE TITLE
Hunter: Cat ability usage

### ISSUE THREAD

**Issue by adocoD** [wowsims/sod#173]
Currently in sims Cats will only use Bite once at the start of the fight.

They should try to prioritize Bite whenever it is off cooldown.

**Comment by rosenrusinov** [comment]
The way we have it is how the games auto cast works for pets. If you have both abilities on autocast it will cast the higher cost one once and then never pool enough energy to cast it again. 

I looked at logs and most people cast bite once and then never again due to most people not handling their pet abilities manually but leaving them on auto casta

**Comment by kayla-glick** [comment]
Oh sounds like we should revert the change I made then @rosenrusinov

**Comment by rosenrusinov** [comment]
Im waiting to see what the community wants as both ways are valid with the second requiring a lot more attention and input

**Comment by adocoD** [comment]
Bite is a 10s cd, while it's still hard to optimally use it most top parsers do have quite a couple of bites in their logs.

https://sod.warcraftlogs.com/reports/dJvNtnY3c7q4rHyW#fight=29&type=damage-done&source=1&ability=-883
https://sod.warcraftlogs.com/reports/1YcPTNw79dtHqy4m#fight=13&type=damage-done&source=16
https://sod.warcraftlogs.com/reports/Lt4PYK31CcnwzHZW#fight=25&type=damage-done&source=3&ability=-883
