### ISSUE TITLE
Rogue/talent/muder is effective for mecanical units

### ISSUE THREAD

**Issue by joexi** [wowsims/sod#371]
Rogue/talent/muder is effective for mecanical units,but mecanical unit is not included by talent description
![image](https://github.com/wowsims/sod/assets/3711488/b25fd3e4-04e6-4ab0-ad2a-5010c80cf96e)

**Comment by vigo2** [comment]
"Mostly" fixed in https://github.com/wowsims/sod/pull/380. Murder and other "Apply Aura: Mod All Damage Done Against Creature" effects change both damage damage _and_ crit damage multiplier in Classic and TBC, e.g. they work like Hunter's Monster or Humanoid Slaying.
The crit damage parts needs some framework rework, so postponing for now.
