### ISSUE TITLE
Warlock - Talent Shadow Mastery not giving any bonus to any dot

### ISSUE THREAD

**Issue by DipsyHyb** [wowsims/sod#976]
The talent "Shadow Mastery" has no effect on dots at all.
Below images are the result of the exact same sim, once with and once without the talent (see the 10% in shadow bolt damage)
<img width="526" alt="image" src="https://github.com/user-attachments/assets/ac5bddc2-9d3e-43d7-bc46-bfc6bcb1ef25">
<img width="544" alt="image" src="https://github.com/user-attachments/assets/ed3acfa8-6fca-4b2e-b895-4b853cf92aa4">

The talent should also give a 10% bonus to dots. (haunt also does not seem to be affected)

Link without shadowmastery
https://wowsims.github.io/sod/warlock/#eJztVU1IVFEUfue+N86dOz67Xi2eN4tpSn1NGHeePtGSZnIRIS1ctBCEIMGo6EcaCNuFGPSnGUGYLYoWZYuiJGhZLqoRIi0qWrQo2lRQCZaWmzrvzZSD6SL6XXQW751zz3e+c969557HFlDCiYJa2ArtkCZp2E929RJoKLFggMAVAkkYBbgC684S+AjoBaHJT/ksr2nH5n1tezi16iM0dg5YmH94ZVrPw/bNbskMPjRpsiCfGDetI6vR1zVhWkdX29dHLTTeI/BFgf3wvmd8QuNpgX0Loyh/N27alxBD+eQr077bKREwnqE93leCxhQax4L2aKeHvjFp2se7FqI2MmXaPagZ/AzmNfjbES/7bUyaLmIaLpyfNJ1lVOeh9aQJmklH8UEI9AI5C/oAwAPQnkBwDAJpIKvuGewZ0f7LbxXxEv52CX9KXhOtYV4tYJslAVvPv2eNi6pdpRy3SsUdR8UrK13lKke5cXwoFW/Sm6FV2/4mYOmsiFGZxww61gPRIAswvdJNsfksJNGg3S12KEoZ+iudla5g0sfyqV7zm473QVTJOLNFOSuMzaN5gjRq0meKI5O3ZAjSml1yVZnEF+/a9gNBjpsJmmgVtRRkNVsuKpiIclYwCGFBeAArvdViG99RqZT/FZ5PRORiJmLc40W//01qpZvyNHr9BNh5okwunYmoQkQn5CPHaeSQ+mHQRM3XAhCqC33QyGarVcovIPB9ARdbkN6W5YzHCrIFIjkjNakGge4hdHPIhKidqa9bS3FQiQpZNktUIXpxoOUGzU1/bQb93JQ49XKBa2Q9s8QCFhoEr5w7OBND/YanXr660IlkGwd1Vuwn6puRqFo6rFTI3HgzGs7hmDVqBR5xxSwFFuFBDeFBGbngxbLU33R9ulvi2GLfNj0spxu5PQ0dJ+FQdjDUJT8SeEagH7RzhAmKvymIBG2I3tRDGcSmZGFGKU6W9J/yZDhRl1kZTSzZ4svjhNOr0yedpqAb2va27YjUKCsR+8fmu30o+Ut4yi/9FA+Xn39NHShx/9l+IVm3bffYgeGNjxJrs55kM3wB9//g8Q==

Link with shadow mastery
https://wowsims.github.io/sod/warlock/#eJztVU1IVFEUfue+N86dOz29Xk2eN4lpSn1NGHeePtGKZnIRES1ctBCEIMGo6EcaiNqFGGRlGUGULYoWZQujJGhZLqoRIi0qWrQo2lRQCZaWBHXem1EHtUX0u+gs3jvnnu9857x7zz2PlVDCiYI62AptkCZpOEB2dRNoKLWgl8BVAkkYBrgKa88T+AToBaHJL/NYXuOOzftb93BqrYrQ2AVgYf7xtWm9CNu3uiQz+MC4yYJ8bNS0jqxEX8eYaR1dad8YttD4gMCX+fajB57xGY1n+fZtjKL8/ahp9yGG8vHXpn2vXSJgNEN74nQpGhNoHA/aw+0e+ua4aZ/oWIDa0IRpH0PN4Ocwr8HfDXnZ72DSdBHTcOHiuOksoToPrSON0ET2FR+CQDeQ86D3AjwE7SkERyCQBrLivsGeE+2//FYRr+Bvl/Cn5A3RGgrqANssCdh6/j1bH6lxlXLcahV3HBVXyq2qcpWrHOXG8aFUvFFvghZt+9uApbMiRmUeM+jIMYgGWYDpVW6KzWchiQbtarZDUcrQX+UsdwWTPpZPdJtTOl4JUS3jzBYVrDBWQPMEWa9JnymOTN6SIUhLdslV5RJfvGPbDwQ5biZorEXUUZA1bKmoZCLKWX4/hAXhAaz0drNtzKJSKf8rPJ+IyIVMxLjHi37/m9RyN+Vp9MZJsPNEuVw8E1GNiHaYhxxnkUPqh0ETtZMFIFQXer+RzVanlF9AYHYBl5uR3pYVjMfyswUiOSO1qQaB7gF0c8iEqJ2pya2lOKtEpSyfI6oQvTjTcoO+T399Bv33KXHw5QJXy1XMEiUs1A9eOXdxLIZ6DE+9cm2BE8k2Duqs2E90ekaiGumwMiFz481oOIdjzqhleMSVcxRYhAc1gAdl5IIXyjJ/0/Xpbolji01telhON3JbGvadgs7sbKhPfiLwnEAPaBcIExT/VBAJ2hC9pYcyiE3JwoxSnCztOePJYKI+szKcWLTFlycJp1unT9tNQTe07m3dEalVViL2j414uzP5S3gq+n6Kh8uvv6YOlLj/bLuUrN+2e+Tg4MbHiTVZT7IJvgEH5+GM

As a note: Demonic Sacrifice and Master Demonologist work fine, which is why I noticed this in the first place. The difference in corruption dmg just seemed odd.

**Comment by DipsyHyb** [comment]
I did some ingame investigation. Drain life (5% for whatever reason) and agony (only base dmg) seem to be correct in the sims. UA, Corruption and Haunt should get the full 10% though.

**Comment by TinkywinkyHYB** [comment]
We tested this on life servers: Here are some images:
Corruption fully benefits, first 3 ticks are without talent, the later one are with talent: 
![corruption](https://github.com/user-attachments/assets/8a06244e-5ad8-48ac-98c0-5d54f1763a87)

Unstable Affliction fully benefits, Agony base partially benefits:
Without talent:
![UA_AGONY](https://github.com/user-attachments/assets/0a46c1c3-3b8f-4d48-bb3b-6dcd0b997cd3)
With Talent:
![UA_AGONY_2](https://github.com/user-attachments/assets/00a36148-798b-4356-90ef-3880e58b9df0)

Drain life partially benefits:
Without talent:
![DRAIN_LIFE](https://github.com/user-attachments/assets/bc33cdf7-ddcd-49ba-b546-c55d475eb582)
With talent:
![DRAIN_LIFE2](https://github.com/user-attachments/assets/a43e2294-e8b2-4132-aae3-df1ffc17a460)

Haunt is harder to tell due to damage range. We believe it fully benefits.
Without talent. Min: 445, Max: 495
![HAUNTS](https://github.com/user-attachments/assets/1d734225-b5d1-4c27-b935-d887e4839309)
With talent. Min: 490, Max: 543
![HAUNT2](https://github.com/user-attachments/assets/69b3e8a5-e69b-498f-8907-b276ebd8b266)

**Comment by TinkywinkyHYB** [comment]
Quick look in the files gave me this idea:

Looking at the [talent file](https://github.com/wowsims/sod/blob/master/sim/warlock/talents.go#L201)
- for UA and corruption: they fail the `!spell.Flags.Matches(core.SpellFlagPureDot)`. Not sure what this flag is used for other than shadow mastery
- Haunt fails the `isWarlockSpell(spell)` because it is missing a warlock flag
- drain life and agony are correct

Didn't check shadowflame.

**Comment by kayla-glick** [comment]
Thanks @TinkywinkyHYB @DipsyHyb! What y'all found matches up with what's on Wowhead https://www.wowhead.com/classic/spell=18275/shadow-mastery. I'm updating the code so that it will correctly apply to Corruption, Haunt, and Unstable Affliction with a 10% full damage multiplier

**Comment by kayla-glick** [comment]
This should be fixed now

Without SM

![Image](https://github.com/user-attachments/assets/621220fd-e3e4-42de-84ab-73b11ad86523)

With SM

![Image](https://github.com/user-attachments/assets/ba6157d5-fd5c-4483-9792-ae79672f0856)
